### ISSUE TITLE
cannot publish

### ISSUE THREAD

**Issue by des-des** [dwyl/ampl#12]
not sure whether I should hold off till this is more complete before publishing..
atm the version of [ampl](https://www.npmjs.com/package/ampl) published before this project was moved into dwyl is blocking me (i think).

**Comment by nelsonic** [comment]
@des-des are you referring to publishing on NPM? is your NPM username the same as on GitHub?

**Comment by nelsonic** [comment]
I've added you as colab on NPM. :+1:

**Comment by des-des** [comment]
![image](https://cloud.githubusercontent.com/assets/12845233/12455414/7fed472a-bf93-11e5-83f9-e626b94306bc.png)
woop
