### ISSUE TITLE
No Coverage Information Collected using Istanbul ... Babel...?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/ampl#17]
At the moment when attempting to run the tests using `istanbul` to collect *coverage* stats, we get:
>"**No coverage information was collected, exit without writing coverage information**"

![dwyl-ampl-no-coverage-info-collected](https://cloud.githubusercontent.com/assets/194400/12457656/aa286290-bf9d-11e5-9387-9e81c32714a3.png)

I suspect this *might* have something to do with: 
https://github.com/gotwarlost/istanbul/issues/262#issuecomment-168280240

We should *investigate* ***why*** `istanbul` :broken_heart: `babel` ...

**Comment by nelsonic** [comment]
Build passes on Travis, but no coverage info collected: https://travis-ci.org/dwyl/ampl/builds/103661684#L272

**Comment by des-des** [comment]
easy quick fix is to write tests in es5

**Comment by nelsonic** [comment]
@des-des agree that when no **ES6** *amazing* benefits are required we should `default` to using ***ES6*** *however* at the moment the *tests* are `import`ing the `src` files ... 
so we would need to switch to using the `lib/ampl.js` instead which would mean running `npm run build` *before* running the tests...

**Comment by des-des** [comment]
ops I think we are both pushing solutions to this. my bad.

**Comment by nelsonic** [comment]
@des-des if you have time to investigate #17 please *assign* to yourself and I'm happy to work on other stuff. you'll probably figure it out fastererer than me... :racehorse:

**Comment by des-des** [comment]
ill give it a go

**Comment by iteles** [comment]
@des-des <3

**Comment by nelsonic** [comment]
@des-des did you see: https://github.com/ambitioninc/babel-istanbul/issues/51#issuecomment-173326875 ?
I've *just* pushed a commit that ***might*** work... https://travis-ci.org/dwyl/ampl/builds/103678920 
promise I will leave it alone after that last commit. need to catch up on work...
hope you're having a good evening. (*don't work toooo hard...*)

**Comment by des-des** [comment]
maybe have too much fun..
