### ISSUE TITLE
bad image crashes ampl

### ISSUE THREAD

**Issue by des-des** [dwyl/ampl#19]
When the module image-size tries to find the dimensions of an image which it does not support it throws an error. This error then crashes ampl..

**Comment by nelsonic** [comment]
Bug...? sounds more like an *undocumented feature*... :wink:

**Comment by des-des** [comment]
Yeah.. maybe an *enhancement* to ampl would be to drop the error while logging that there was a problem?

**Comment by nelsonic** [comment]
@des-des it *depends* on how the `ampl` package is going to be *used*...

**Comment by des-des** [comment]
ok gonna go with console.warn for now. Maybe later can catch the errors higher up and expose them to the developer using ampl so that they can decide what to do.
