### ISSUE TITLE
markdown2AmpHTML emits <!doctype html> 

### ISSUE THREAD

**Issue by puppetmaster3** [dwyl/ampl#32]
great project.
<!doctype html> is a head tag.

Bug:
var markdownString = '# Hello World!' // or read from a .md file
ampl.markdown2AmpHTML({markdown:markdownString}, function(ampHtml) {
  console.log(ampHtml)
})
emits
<!doctype html><h1 >Hello World!</h1>

<!doctype html> should not be emitted in the body. parseHtml() appears to put it no matter what to start. This bug also works if you use parse w/ headOverride: '' //empty header.

**Comment by pankajpatel** [comment]
https://runkit.com/pankaj/ampl-test

The doctype is appearing with markup. Opening a PR for the fix.
